name: C/C++ CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y libpcap-dev
    - name: Build project
      run: make
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: spd
