name: C/C++ CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: install deps
      run: sudo apt install -y libpcap-dev
    - name: make
      run: make
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: spd
